package com.amazon.sbidoo.game.status.util;

import com.amazon.sbidoo.game.status.Board;
import com.amazon.sbidoo.game.status.Space;
import com.google.common.collect.ImmutableMap;

final public class BoardCreationHelper {
    private BoardCreationHelper() {
    }

    public static Board createBoard() {
        return Board.builder()
                .spaceMap(ImmutableMap.<Integer, Space>builder()
                        .put(0, Space.builder()
                                .spaceCategory(Space.SpaceCategory.Other)
                                .spaceType(Space.SpaceType.Start)
                                .spaceName("start")
                                .price(0)
                                .build())
                        .put(1, Space.builder()
                                .spaceType(Space.SpaceType.Property)
                                .spaceCategory(Space.SpaceCategory.Brown)
                                .spaceName("Mediterranean Avenue")
                                .price(60)
                                .build())
                        .put(2, Space.builder()
                                .spaceType(Space.SpaceType.CommunityChest)
                                .spaceCategory(Space.SpaceCategory.Other)
                                .spaceName("Baltic Avenue")
                                .price(60)
                                .build())
                        .put(3, Space.builder()
                                .spaceType(Space.SpaceType.Property)
                                .spaceCategory(Space.SpaceCategory.Brown)
                                .spaceName("Baltic Avenue")
                                .price(60)
                                .build())
                        .put(4, Space.builder()
                                .spaceType(Space.SpaceType.IncomeTax)
                                .spaceCategory(Space.SpaceCategory.Other)
                                .price(200)
                                .spaceName("Income Tax")
                                .build())
                        .put(5, Space.builder()
                                .spaceType(Space.SpaceType.RailRoad)
                                .spaceCategory(Space.SpaceCategory.RailRoad)
                                .price(200)
                                .spaceName("Reading Railroad")
                                .build())
                        .put(6, Space.builder()
                                .spaceType(Space.SpaceType.Property)
                                .spaceCategory(Space.SpaceCategory.LightBlue)
                                .price(100)
                                .spaceName("Oriental Avenue")
                                .build())
                        .put(7, Space.builder()
                                .spaceType(Space.SpaceType.Chance)
                                .spaceCategory(Space.SpaceCategory.Other)
                                .price(0)
                                .spaceName("Chance")
                                .build())
                        .put(8, Space.builder()
                                .spaceType(Space.SpaceType.Property)
                                .spaceCategory(Space.SpaceCategory.LightBlue)
                                .price(100)
                                .spaceName("Vermont Avenue")
                                .build())
                        .put(9, Space.builder()
                                .spaceType(Space.SpaceType.Property)
                                .spaceCategory(Space.SpaceCategory.LightBlue)
                                .price(100)
                                .spaceName("Connecticut Avenue")
                                .build())
                        .put(10, Space.builder()
                                .spaceType(Space.SpaceType.Jail)
                                .spaceCategory(Space.SpaceCategory.Other)
                                .price(0)
                                .spaceName("Jail")
                                .build())
                        .put(11, Space.builder()
                                .spaceType(Space.SpaceType.Property)
                                .spaceCategory(Space.SpaceCategory.Pink)
                                .price(140)
                                .spaceName("St. Charles Place")
                                .build())
                        .put(12, Space.builder()
                                .spaceType(Space.SpaceType.Utilities)
                                .spaceCategory(Space.SpaceCategory.Utilities)
                                .price(150)
                                .spaceName("Electric Company")
                                .build())
                        .put(13, Space.builder()
                                .spaceType(Space.SpaceType.Property)
                                .spaceCategory(Space.SpaceCategory.Pink)
                                .price(140)
                                .spaceName("State Avenue")
                                .build())
                        .put(14, Space.builder()
                                .spaceType(Space.SpaceType.Property)
                                .spaceCategory(Space.SpaceCategory.Pink)
                                .price(150)
                                .spaceName("Virginia Avenue")
                                .build())
                        .put(15, Space.builder()
                                .spaceType(Space.SpaceType.RailRoad)
                                .spaceCategory(Space.SpaceCategory.RailRoad)
                                .price(200)
                                .spaceName("Pennsylvania Railroad")
                                .build())
                        .put(16, Space.builder()
                                .spaceType(Space.SpaceType.Property)
                                .spaceCategory(Space.SpaceCategory.Orange)
                                .price(180)
                                .spaceName("St. James Place")
                                .build())
                        .put(17, Space.builder()
                                .spaceType(Space.SpaceType.CommunityChest)
                                .spaceCategory(Space.SpaceCategory.Other)
                                .price(0)
                                .spaceName("Community Chest")
                                .build())
                        .put(18, Space.builder()
                                .spaceType(Space.SpaceType.Property)
                                .spaceCategory(Space.SpaceCategory.Orange)
                                .price(180)
                                .spaceName("Tennessee Avenue")
                                .build())
                        .put(19, Space.builder()
                                .spaceType(Space.SpaceType.Property)
                                .spaceCategory(Space.SpaceCategory.Orange)
                                .price(200)
                                .spaceName("New York Avenue")
                                .build())
                        .put(20, Space.builder()
                                .spaceType(Space.SpaceType.FreeParking)
                                .spaceCategory(Space.SpaceCategory.Other)
                                .price(0)
                                .spaceName("Free Parking")
                                .build())
                        .put(21, Space.builder()
                                .spaceType(Space.SpaceType.Property)
                                .spaceCategory(Space.SpaceCategory.Red)
                                .price(220)
                                .spaceName("Kentucky Avenue")
                                .build())
                        .put(22, Space.builder()
                                .spaceType(Space.SpaceType.Chance)
                                .spaceCategory(Space.SpaceCategory.Other)
                                .price(0)
                                .spaceName("Chance")
                                .build())
                        .put(23, Space.builder()
                                .spaceType(Space.SpaceType.Property)
                                .spaceCategory(Space.SpaceCategory.Red)
                                .price(220)
                                .spaceName("Indiana Avenue")
                                .build())
                        .put(24, Space.builder()
                                .spaceType(Space.SpaceType.Property)
                                .spaceCategory(Space.SpaceCategory.Red)
                                .price(240)
                                .spaceName("Illinois Avenue")
                                .build())
                        .put(25, Space.builder()
                                .spaceType(Space.SpaceType.RailRoad)
                                .spaceCategory(Space.SpaceCategory.RailRoad)
                                .price(200)
                                .spaceName("B and O Railroad")
                                .build())
                        .put(26, Space.builder()
                                .spaceType(Space.SpaceType.Property)
                                .spaceCategory(Space.SpaceCategory.Yellow)
                                .price(260)
                                .spaceName("Atlantic Avenue")
                                .build())
                        .put(27, Space.builder()
                                .spaceType(Space.SpaceType.Property)
                                .spaceCategory(Space.SpaceCategory.Yellow)
                                .price(260)
                                .spaceName("Ventnor Avenue")
                                .build())
                        .put(28, Space.builder()
                                .spaceType(Space.SpaceType.Utilities)
                                .spaceCategory(Space.SpaceCategory.Utilities)
                                .price(150)
                                .spaceName("Water Works")
                                .build())
                        .put(29, Space.builder()
                                .spaceType(Space.SpaceType.Property)
                                .spaceCategory(Space.SpaceCategory.Yellow)
                                .price(280)
                                .spaceName("Marvin Gardens")
                                .build())
                        .put(30, Space.builder()
                                .spaceType(Space.SpaceType.GoToJail)
                                .spaceCategory(Space.SpaceCategory.Other)
                                .price(0)
                                .spaceName("Go to jail")
                                .build())
                        .put(31, Space.builder()
                                .spaceType(Space.SpaceType.Property)
                                .spaceCategory(Space.SpaceCategory.Green)
                                .price(300)
                                .spaceName("Pacific Avenue")
                                .build())
                        .put(32, Space.builder()
                                .spaceType(Space.SpaceType.Property)
                                .spaceCategory(Space.SpaceCategory.Green)
                                .price(300)
                                .spaceName("North Carolina Avenue")
                                .build())
                        .put(33, Space.builder()
                                .spaceType(Space.SpaceType.CommunityChest)
                                .spaceCategory(Space.SpaceCategory.Other)
                                .price(0)
                                .spaceName("Community Chest")
                                .build())
                        .put(34, Space.builder()
                                .spaceType(Space.SpaceType.Property)
                                .spaceCategory(Space.SpaceCategory.Green)
                                .price(320)
                                .spaceName("Pennsylvania Avenue")
                                .build())
                        .put(35, Space.builder()
                                .spaceType(Space.SpaceType.RailRoad)
                                .spaceCategory(Space.SpaceCategory.RailRoad)
                                .price(200)
                                .spaceName("Short Line")
                                .build())
                        .put(36, Space.builder()
                                .spaceType(Space.SpaceType.Chance)
                                .spaceCategory(Space.SpaceCategory.Other)
                                .price(0)
                                .spaceName("Chance")
                                .build())
                        .put(37, Space.builder()
                                .spaceType(Space.SpaceType.Property)
                                .spaceCategory(Space.SpaceCategory.Blue)
                                .price(350)
                                .spaceName("Park Place")
                                .build())
                        .put(38, Space.builder()
                                .spaceType(Space.SpaceType.LuxuryTax)
                                .spaceCategory(Space.SpaceCategory.Other)
                                .price(100)
                                .spaceName("Luxury Tax")
                                .build())
                        .put(39, Space.builder()
                                .spaceType(Space.SpaceType.Property)
                                .spaceCategory(Space.SpaceCategory.Blue)
                                .price(400)
                                .spaceName("Boardwalk")
                                .build())
                        .build())
                .build();
    }
}
